"""treasury: cuenta corriente y caja

Revision ID: 0d72d1262cdc
Revises: 967b63458ae1
Create Date: 2026-07-25 00:54:30.577013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d72d1262cdc'
down_revision: Union[str, Sequence[str], None] = '967b63458ae1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cash_sessions',
    sa.Column('opening_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('opened_by_user_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', name='cash_session_status', native_enum=False, length=10), server_default='OPEN', nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('closing_amount_declared', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('closing_amount_expected', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['closed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['opened_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cash_sessions_tenant_id'), 'cash_sessions', ['tenant_id'], unique=False)
    op.create_index('uq_cash_sessions_one_open_per_tenant', 'cash_sessions', ['tenant_id'], unique=True, postgresql_where=sa.text("status = 'OPEN'"))
    op.create_table('account_movements',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('DEBIT', 'CREDIT', name='account_movement_type', native_enum=False, length=10), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('sale_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_account_movements_amount_positive'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_movements_customer_id'), 'account_movements', ['customer_id'], unique=False)
    op.create_index(op.f('ix_account_movements_sale_id'), 'account_movements', ['sale_id'], unique=False)
    op.create_index(op.f('ix_account_movements_tenant_id'), 'account_movements', ['tenant_id'], unique=False)
    op.create_table('cash_movements',
    sa.Column('cash_session_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('INCOME', 'EXPENSE', name='cash_movement_type', native_enum=False, length=10), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('sale_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_cash_movements_amount_positive'),
    sa.ForeignKeyConstraint(['cash_session_id'], ['cash_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cash_movements_cash_session_id'), 'cash_movements', ['cash_session_id'], unique=False)
    op.create_index(op.f('ix_cash_movements_sale_id'), 'cash_movements', ['sale_id'], unique=False)
    op.create_index(op.f('ix_cash_movements_tenant_id'), 'cash_movements', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cash_movements_tenant_id'), table_name='cash_movements')
    op.drop_index(op.f('ix_cash_movements_sale_id'), table_name='cash_movements')
    op.drop_index(op.f('ix_cash_movements_cash_session_id'), table_name='cash_movements')
    op.drop_table('cash_movements')
    op.drop_index(op.f('ix_account_movements_tenant_id'), table_name='account_movements')
    op.drop_index(op.f('ix_account_movements_sale_id'), table_name='account_movements')
    op.drop_index(op.f('ix_account_movements_customer_id'), table_name='account_movements')
    op.drop_table('account_movements')
    op.drop_index('uq_cash_sessions_one_open_per_tenant', table_name='cash_sessions', postgresql_where=sa.text("status = 'OPEN'"))
    op.drop_index(op.f('ix_cash_sessions_tenant_id'), table_name='cash_sessions')
    op.drop_table('cash_sessions')
    # ### end Alembic commands ###
