"""product categories catalog + is_active

Revision ID: 3f23358dfb7a
Revises: 0d72d1262cdc
Create Date: 2026-07-27 17:05:20.241604

"""
import uuid
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f23358dfb7a'
down_revision: Union[str, Sequence[str], None] = '0d72d1262cdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_categories',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_product_categories_tenant_id_name')
    )
    op.create_index(op.f('ix_product_categories_tenant_id'), 'product_categories', ['tenant_id'], unique=False)
    op.add_column('products', sa.Column('category_id', sa.UUID(), nullable=True))
    op.add_column('products', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.create_index(op.f('ix_products_category_id'), 'products', ['category_id'], unique=False)
    op.create_foreign_key(None, 'products', 'product_categories', ['category_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###

    # Migración de datos, a mano (no autogenerada): antes de dropear
    # 'category' (texto libre), cada valor distinto por tenant se da de
    # alta en product_categories y los productos que lo usaban quedan
    # apuntando ahí vía category_id. Sin esto, cualquier producto con
    # categoría cargada la perdería en silencio al dropear la columna.
    bind = op.get_bind()
    distinct_categories = bind.execute(
        sa.text(
            "SELECT DISTINCT tenant_id, category FROM products WHERE category IS NOT NULL"
        )
    ).fetchall()
    for tenant_id, category_name in distinct_categories:
        category_id = uuid.uuid4()
        bind.execute(
            sa.text(
                "INSERT INTO product_categories (id, tenant_id, name, created_at) "
                "VALUES (:id, :tenant_id, :name, now())"
            ),
            {"id": category_id, "tenant_id": tenant_id, "name": category_name},
        )
        bind.execute(
            sa.text(
                "UPDATE products SET category_id = :category_id "
                "WHERE tenant_id = :tenant_id AND category = :name"
            ),
            {"category_id": category_id, "tenant_id": tenant_id, "name": category_name},
        )

    op.drop_column('products', 'category')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###

    # Reversa de la migración de datos de arriba, antes de dropear
    # category_id/product_categories.
    bind = op.get_bind()
    bind.execute(
        sa.text(
            "UPDATE products SET category = pc.name "
            "FROM product_categories pc WHERE products.category_id = pc.id"
        )
    )

    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_index(op.f('ix_products_category_id'), table_name='products')
    op.drop_column('products', 'is_active')
    op.drop_column('products', 'category_id')
    op.drop_index(op.f('ix_product_categories_tenant_id'), table_name='product_categories')
    op.drop_table('product_categories')
