"""tenant_profile_and_logo

Revision ID: 4c3d63b61f4f
Revises: 588d0c9b73f9
Create Date: 2026-07-27 22:01:46.245321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c3d63b61f4f'
down_revision: Union[str, Sequence[str], None] = '588d0c9b73f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('cuit', sa.String(), nullable=True))
    op.add_column('tenants', sa.Column('address', sa.String(), nullable=True))
    op.add_column('tenants', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('tenants', sa.Column('business_email', sa.String(), nullable=True))
    op.add_column('tenants', sa.Column('tax_status', sa.Enum('RESPONSABLE_INSCRIPTO', 'MONOTRIBUTO', 'EXENTO', name='tenant_tax_status', native_enum=False, length=30), nullable=True))
    op.add_column('tenants', sa.Column('logo', sa.LargeBinary(), nullable=True))
    op.add_column('tenants', sa.Column('logo_content_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'logo_content_type')
    op.drop_column('tenants', 'logo')
    op.drop_column('tenants', 'tax_status')
    op.drop_column('tenants', 'business_email')
    op.drop_column('tenants', 'phone')
    op.drop_column('tenants', 'address')
    op.drop_column('tenants', 'cuit')
    # ### end Alembic commands ###
