"""add product cost/category/sku/barcode/image_url and product_variants table

Revision ID: 6e8d9c8f708f
Revises: e52e63ae983f
Create Date: 2026-07-09 16:11:40.874745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6e8d9c8f708f'
down_revision: Union[str, Sequence[str], None] = 'e52e63ae983f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_variants',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('stock >= 0', name='ck_product_variants_stock_non_negative'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_variants_product_id'), 'product_variants', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_variants_tenant_id'), 'product_variants', ['tenant_id'], unique=False)
    op.add_column('products', sa.Column('cost', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('products', sa.Column('category', sa.String(), nullable=True))
    op.add_column('products', sa.Column('sku', sa.String(), nullable=True))
    op.add_column('products', sa.Column('barcode', sa.String(), nullable=True))
    op.add_column('products', sa.Column('image_url', sa.String(), nullable=True))
    op.create_unique_constraint('uq_products_tenant_id_sku', 'products', ['tenant_id', 'sku'])
    # Autogenerate no detecta CHECK constraints agregados sobre una
    # tabla ya existente (sólo los renderiza inline en create_table) --
    # agregado a mano, ver models.py: Product.__table_args__.
    op.create_check_constraint('ck_products_cost_positive', 'products', 'cost > 0')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_products_cost_positive', 'products', type_='check')
    op.drop_constraint('uq_products_tenant_id_sku', 'products', type_='unique')
    op.drop_column('products', 'image_url')
    op.drop_column('products', 'barcode')
    op.drop_column('products', 'sku')
    op.drop_column('products', 'category')
    op.drop_column('products', 'cost')
    op.drop_index(op.f('ix_product_variants_tenant_id'), table_name='product_variants')
    op.drop_index(op.f('ix_product_variants_product_id'), table_name='product_variants')
    op.drop_table('product_variants')
    # ### end Alembic commands ###
