"""order_notes

Revision ID: 703e3e0ade7b
Revises: 76095d28bcc5
Create Date: 2026-07-30 22:36:43.422852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '703e3e0ade7b'
down_revision: Union[str, Sequence[str], None] = '76095d28bcc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_notes',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='ARS', nullable=False),
    sa.Column('order_note_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'INVOICED', 'CANCELLED', name='order_note_status', native_enum=False, length=20), server_default='PENDING', nullable=False),
    sa.Column('sale_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('total_amount > 0', name='ck_order_notes_total_amount_positive'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'order_note_number', name='uq_order_notes_tenant_id_order_note_number')
    )
    op.create_index(op.f('ix_order_notes_customer_id'), 'order_notes', ['customer_id'], unique=False)
    op.create_index(op.f('ix_order_notes_sale_id'), 'order_notes', ['sale_id'], unique=False)
    op.create_index(op.f('ix_order_notes_tenant_id'), 'order_notes', ['tenant_id'], unique=False)
    op.create_table('order_note_items',
    sa.Column('order_note_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('variant_id', sa.UUID(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_order_note_items_quantity_positive'),
    sa.CheckConstraint('unit_price > 0', name='ck_order_note_items_unit_price_positive'),
    sa.ForeignKeyConstraint(['order_note_id'], ['order_notes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_note_items_order_note_id'), 'order_note_items', ['order_note_id'], unique=False)
    op.create_index(op.f('ix_order_note_items_product_id'), 'order_note_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_order_note_items_tenant_id'), 'order_note_items', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_order_note_items_variant_id'), 'order_note_items', ['variant_id'], unique=False)
    op.add_column('tenants', sa.Column('next_order_note_number', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'next_order_note_number')
    op.drop_index(op.f('ix_order_note_items_variant_id'), table_name='order_note_items')
    op.drop_index(op.f('ix_order_note_items_tenant_id'), table_name='order_note_items')
    op.drop_index(op.f('ix_order_note_items_product_id'), table_name='order_note_items')
    op.drop_index(op.f('ix_order_note_items_order_note_id'), table_name='order_note_items')
    op.drop_table('order_note_items')
    op.drop_index(op.f('ix_order_notes_tenant_id'), table_name='order_notes')
    op.drop_index(op.f('ix_order_notes_sale_id'), table_name='order_notes')
    op.drop_index(op.f('ix_order_notes_customer_id'), table_name='order_notes')
    op.drop_table('order_notes')
    # ### end Alembic commands ###
