"""sale_items variant_id

Revision ID: 91de20230477
Revises: bb1978619a5a
Create Date: 2026-07-22 21:20:14.004325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91de20230477'
down_revision: Union[str, Sequence[str], None] = 'bb1978619a5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sale_items', sa.Column('variant_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_sale_items_variant_id'), 'sale_items', ['variant_id'], unique=False)
    op.create_foreign_key(
        'fk_sale_items_variant_id', 'sale_items', 'product_variants',
        ['variant_id'], ['id'], ondelete='RESTRICT',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_sale_items_variant_id', 'sale_items', type_='foreignkey')
    op.drop_index(op.f('ix_sale_items_variant_id'), table_name='sale_items')
    op.drop_column('sale_items', 'variant_id')
    # ### end Alembic commands ###
