"""add sku to product_variants

Revision ID: bb0ba2b854b1
Revises: 6e8d9c8f708f
Create Date: 2026-07-13 14:57:54.194694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb0ba2b854b1'
down_revision: Union[str, Sequence[str], None] = '6e8d9c8f708f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_variants', sa.Column('sku', sa.String(), nullable=True))
    op.create_unique_constraint('uq_product_variants_tenant_id_sku', 'product_variants', ['tenant_id', 'sku'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_product_variants_tenant_id_sku', 'product_variants', type_='unique')
    op.drop_column('product_variants', 'sku')
    # ### end Alembic commands ###
