"""add customer_types table and credit_limit/default_salesperson/customer_type on customers

Revision ID: bb1978619a5a
Revises: bb0ba2b854b1
Create Date: 2026-07-13 20:27:10.246849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb1978619a5a'
down_revision: Union[str, Sequence[str], None] = 'bb0ba2b854b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_types',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_customer_types_tenant_id_name')
    )
    op.create_index(op.f('ix_customer_types_tenant_id'), 'customer_types', ['tenant_id'], unique=False)
    op.add_column('customers', sa.Column('credit_limit', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('customers', sa.Column('default_salesperson_id', sa.UUID(), nullable=True))
    op.add_column('customers', sa.Column('customer_type_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_customers_customer_type_id'), 'customers', ['customer_type_id'], unique=False)
    op.create_index(op.f('ix_customers_default_salesperson_id'), 'customers', ['default_salesperson_id'], unique=False)
    op.create_foreign_key(
        'fk_customers_customer_type_id', 'customers', 'customer_types',
        ['customer_type_id'], ['id'], ondelete='SET NULL',
    )
    op.create_foreign_key(
        'fk_customers_default_salesperson_id', 'customers', 'users',
        ['default_salesperson_id'], ['id'], ondelete='SET NULL',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_customers_default_salesperson_id', 'customers', type_='foreignkey')
    op.drop_constraint('fk_customers_customer_type_id', 'customers', type_='foreignkey')
    op.drop_index(op.f('ix_customers_default_salesperson_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_customer_type_id'), table_name='customers')
    op.drop_column('customers', 'customer_type_id')
    op.drop_column('customers', 'default_salesperson_id')
    op.drop_column('customers', 'credit_limit')
    op.drop_index(op.f('ix_customer_types_tenant_id'), table_name='customer_types')
    op.drop_table('customer_types')
    # ### end Alembic commands ###
