"""sale_card_coupon_authorization

Revision ID: c10b07cb74a7
Revises: 5ca5b81d367a
Create Date: 2026-07-27 20:30:53.568292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c10b07cb74a7'
down_revision: Union[str, Sequence[str], None] = '5ca5b81d367a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('card_coupon_number', sa.String(), nullable=True))
    op.add_column('sales', sa.Column('card_authorization_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales', 'card_authorization_code')
    op.drop_column('sales', 'card_coupon_number')
    # ### end Alembic commands ###
